POST http://localhost:4004/v2/MroSrv/approvePricing
Content-Type: application/json;IEEE754Compatible=true

{
    "uuid": "bbfa1b5c-ff2b-4118-aab8-0c85596278d8",
"manufacturerCode": "PD10",
"countryCode": "IT"
}